apiVersion: release-notes/v2
kind: feature
area: telemetry
releaseNotes:
- |
  **Fixed** an issue where the `cluster_name` label was incorrectly truncated for services without a `.svc.cluster.local` suffix
upgradeNote:
- title: Dots (".") are now sanitized to underscores ("_") for `cluster_name` label values that don't end in `.svc.cluster.local`
  content: |
    Previously, the Envoy cluster metrics for services that did not have a `.svc.cluster.local` suffix
    were incorrectly truncated and parsed. This was due to the fact that Envoy cluster metrics use dots "." as
    a delimeter between metric namespaces, and it is impossible to properly distinguish between those
    delimeters and the dots in hostnames/cluster names. To address this, dots in the `cluster_name` label
    are now sanitized to underscores "_" if that cluster_name does not end in `.svc.cluster.local`.

