apiVersion: release-notes/v2
kind: bug-fix
area: istioctl

releaseNotes:
  - |
    **Fixed** an issue that istioctl cannot install with `pilot.volumes`, `pilot.volumeMounts` and `pilot.extraContainerArgs`.