apiVersion: release-notes/v2
kind: feature
area: traffic-management
issue: []
releaseNotes:
- |
  **Updated** allow specifying the downgraded protocol in the sidecar port definition
upgradeNotes: []
docs: []
securityNotes: []