{{- if .Values.base.enableCRDTemplates }}
{{- range $crd := .Files.Get "crds/crd-all.gen.yaml"|splitList "\n---\n"}}
{{- $name := (index ($crd |fromYaml) "metadata" "name") }}
{{- if not (has $name $.Values.base.excludedCRDs)}}
{{$crd}}
---
{{- end }}
{{- end }}
{{- end }}
