global:
  variant: distroless

# Overrides for the `istiod-remote` dep
istiod:
  profile: ambient

# Overrides for the `ztunnel` dep
ztunnel:
  profile: ambient

# Overrides for the `cni` dep
cni:
  profile: ambient
