pilot:
  env:
    # 1.24 behavioral changes
    ENABLE_INBOUND_RETRY_POLICY: "false"
    EXCLUDE_UNSAFE_503_FROM_DEFAULT_RETRY: "false"
    
meshConfig:
  # 1.22 behavioral changes
  defaultConfig:
    proxyMetadata:
      ENABLE_DEFERRED_CLUSTER_CREATION: "false"