meshConfig:
  defaultConfig:
    proxyMetadata:
      # 1.22 behavioral changes
      ENABLE_DEFERRED_CLUSTER_CREATION: "false"
      # 1.23 behavioral changes
      ENABLE_DELIMITED_STATS_TAG_REGEX": "false"
