meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_ENABLE_HBONE: "true"
global:
  platform: openshift
  variant: distroless
  seLinuxOptions:
    type: spc_t
cni:
  enabled: true
  ambient:
    enabled: true
  logLevel: info
  provider: "multus"
  cniBinDir: /var/lib/cni/bin
  cniConfDir: /etc/cni/multus/net.d
  chained: false
  cniConfFileName: "istio-cni.conf"
  env:
    PILOT_ENABLE_AMBIENT: "true"