# The OpenShift profile provides a basic set of settings to run Istio on OpenShift
# CNI must be installed.
cni:
  cniBinDir: /var/lib/cni/bin
  cniConfDir: /etc/cni/multus/net.d
  chained: false
  cniConfFileName: "istio-cni.conf"
  logLevel: info
global:
  platform: openshift
pilot:
  cniEnabled: true